### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by nowak-ninja** [jodigiordano/gg#31]
Hi, I would like to thank You for this great tool. Using it I have found these feature might be useful for me:

1. Allow flow to be animated as back and forth - just to simplify visualization by showing the communication is going in both directions without having to draw an additional line
2. Allow drawing flow lines to parents. Example: I have a cluster containing several services and I do not want to point to any particular one, just to the cluster.

Thx :)

**Comment by jodigiordano** [comment]
@nowak-ninja 

> Allow flow to be animated as back and forth - just to simplify visualization by showing the communication is going in both directions without having to draw an additional line

Can you provide a link to an example of what you are doing right now as a workaround?

Currently, it is possible to change the direction of the data by clicking multiple times on it. [Here is an example](https://gg-charts.com/viewer.html#=&file=eJy1VE1TgzAQvfdXZOKMJ6YDFZ3Box68OZ68OD0ESDDDR2iIIu3w300CUigZbWN7Ccm+hffe7obdAgBYlTiihEZIUFa8Yl7JB7wH0Fu6Sxc6KkVQkWEVe8Y1qJpK4LwDun0loTd5BGCnVwnQWKXzbZr47zpVR0tWUdF9/idTRr/k0Vs5+0CjAn5/boe3BxVwMQIOKJtN5m6OYfTPxojZZmvnMbBjrG8CRO08WjI2/qcbWXlcWVY1ycn21srjEYxyXev5zWiRGqYXmYY3NIxXTuM4wy9ICMz1pSlpieGc94nRIgGE8Rrx2GwbGWYpNHT7NMoQRelfnNPehobqW9kE14fsQ9lJxmpD2eW/pNyHx5CGU9wQjnLF5DpjgHCWGzrWaWPztmkgRgI9SH0JZx9F/MgyxlXmFb7zAj+EQ2rrWKqZ9m0sRjf5/wTTxo0Ipt371S0h2POCk8R4RjEGzt7tXOXFxZyx9GaCy0xav1vvb8ui/QaHl64e&autoplay=true). As you can see, if you want a piece of data to do a back and forth between two components, you need to create 2 keyframes.

IMO what is missing right now is to be able to do a back & forth on a single keyframe.

> Allow drawing flow lines to parents. Example: I have a cluster containing several services and I do not want to point to any particular one, just to the cluster.

This is an interesting idea for general flowchart diagrams.
I would add "Systems A & B can have more than one link between them" in this lot.

I'm not sure for a software architecture diagram, though.
For example, in your cluster, don't you have a load balancer that take care of the request? [Something like that](https://gg-charts.com/viewer.html#=&file=eJy1lD1vgzAQhnd+heWuKAWSqEq3Nqq6VR2qLlUGY0xkYbBrk69G+e81HyFAHAJKuwA+H6+fO9/d3gIAKkEwDSlGKeXJJ5FKv+AjgO7IGTnQzlxSmjKS2d7IBqidSklcbBTfSm996SUA+/ypN2iQuatAi+WeuVFwRdNC/eiorVu99Cb2ybDThlm5PFQ/VwyYrfSh8iTbhqiD1GC+FZ6uoF3fMAJVUI7dtGVc05rp0NCq+BhHAfARQwmuUeY+PsLRUvJVEsw54zLzvhtjfzLxoWVQNQSx/PGGBeG6hiic61EoItcUE4D6ks3WIprdTNYjv0ey3jmbjVNP3EzmDkgarqGVXwur9l+rTdZbzyV92sT1Wm3iPnT0CWJMF6B1pFjkHctoEhn6FZ13CPTPCw7GNAgYeUep7sB8SggqCDTGdlGyWSl/I9m44sGSrQvwDcd0SVbJDRnfGJKrx5PoGE8R2YUSxaQ9cmAoeXyOV9wyvzDSAqKwpKKsH/j68gHuy7KcX2+YGoprRDGcWKAYBlMHytMgFO8/s/I8CGU8LCuG0dPzgppjI6sw6/ALkRipfA==&autoplay=true).

If you can provide me an example of your diagram, it would help me understand what you are trying to achieve! :pray:

**Comment by jodigiordano** [comment]
Good news: I now support multiple links between systems and linking parent containers.
Bad news: I dropped the flows and I'm pivoting this project to a general diagramming tool. Sorry!
