### ISSUE TITLE
https://gg-charts.com/#=&file=eJy9mE1zmzAQhu... Link No Longer Works

### ISSUE THREAD

**Issue by Stan-Stani** [jodigiordano/gg#33]
I had made a chart a month or so back but it will no longer load.

**Comment by jodigiordano** [comment]
Sorry about that @Stan-Stani, I modified the specification quite a bit in the last month and I did not think about retro-compatibility. I also don't give a lot of details yet when an error occurs at load time.
Both things I need to improve :sweat_smile: 

That said, I can unblock you if you send me the link privately at jodi@gg-charts.com.
If you don't want to share the link, you can look into your browser console (ex: Ctrl+Shift+I in Firefox) for more details.

**Comment by jodigiordano** [comment]
@Stan-Stani Please e-mail me if you need to be unblocked! Thank you!
