### ISSUE TITLE
[Suggestion] General purpose sticky notes/labels

### ISSUE THREAD

**Issue by thngz** [jodigiordano/gg#8]
I think this feature would help with the readability of more complex systems. For example you can add label about the data which is moved down the pipe, add additional comments about some parts of the system, or give "names" to the pipelines to make their use more clear.

**Comment by jodigiordano** [comment]
Thank you for those great suggestions!

I created 3 issues based on them:

- (v1) https://github.com/jodigiordano/gg/issues/13
- (v1) https://github.com/jodigiordano/gg/issues/14
- (tbd) https://github.com/jodigiordano/gg/issues/15
