### ISSUE TITLE
BUG: Middle mouse button drags elements 

### ISSUE THREAD

**Issue by bn-l** [jodigiordano/gg#9]
Middle mouse button (javascript mouse button 4) grabs and drags elements when it should just drag the view.

Very cool project by the way. I will use it in the future I'm sure.

**Comment by jodigiordano** [comment]
Thank you for the bug report, it is very appreciated!

I just pushed a new version that only considers the `left` mouse button when applying an operation.

For some unknown reasons, I am not able to drag the viewport with the middle mouse button. I am using `pixi-viewport` under the hood and by looking at the code, I should be able to perform that operation, but it seems like the middle mouse button event is never triggered.

I'll have to revisit this eventually but for now:

- You can drag the viewport with the `right` mouse button.
- You can drag the viewpotr with the `left` mouse button, when no system is selected.

**Comment by jodigiordano** [comment]
@bn-l I replaced `pixi-viewport` with my own custom code. The middle mouse button can now be used to drag the view.

**Comment by jodigiordano** [comment]
Closing, please re-open if it doesn't work!

**Comment by bn-l** [comment]
@jodigiordano working great. Just didn't some testing. 

Hey what do you think about this: the play/pause button in the corner:

![image](https://github.com/user-attachments/assets/d8fde7e5-7c65-4d5f-84b8-ade4d24791ff)

**Comment by bn-l** [comment]
Also what about having the little green flow widgets light up a bit more, [really pop](https://theoatmeal.com/comics/design_hell):

![image](https://github.com/user-attachments/assets/447d98d6-acb3-4d9b-89c8-fcf1c4e2ef8c)

**Comment by jodigiordano** [comment]
@bn-l oh my, I love that comic! :joy: Yeah those geen dots could use a little lens flare!

I'll create an issue to keep track of that green dot enhancement.

I'm not sure about the play / pause button.
Don't get me wrong, the current controls are awful but I want the UI to play nice in mobile, and that play / pause button in the top-right corner could be problematic.
Also:

- There is a "presentation mode" now that you can use by clicking on "View > presentation mode".
- You can control the flow animation with the keyboard: `<space>` for  play/pause, arrow keys to mode forward/backward in the steps.
